-- ============================================================
-- S.O.S Cursos - RESTAURAR CATÁLOGO (recuperação de emergência)
-- Gerado automaticamente a partir de src/data.ts
-- Como usar: Supabase > SQL Editor > New query > cole > RUN
-- ON CONFLICT (name) DO NOTHING preserva linhas existentes
-- (ex.: preços customizados que já estejam no banco).
-- ============================================================

insert into public.courses (name, category, hours, price, kids) values
  ('3D Studio Max Básico', 'Informática & Tecnologia', 21, 79.9, false),
  ('Access 2016', 'Informática & Tecnologia', 20, 69.9, false),
  ('After Effects', 'Informática & Tecnologia', 15, 69.9, false),
  ('AutoCad 2D e 3D', 'Informática & Tecnologia', 50, 89.9, false),
  ('Bitcoin', 'Informática & Tecnologia', 2, 49.9, false),
  ('Blender 3D', 'Informática & Tecnologia', 22, 79.9, false),
  ('Canva', 'Informática & Tecnologia', 30, 79.9, false),
  ('Como ser um Youtuber', 'Informática & Tecnologia', 4, 59.9, false),
  ('Corel Draw X8', 'Informática & Tecnologia', 6, 59.9, false),
  ('Criação de App Android e iOS', 'Informática & Tecnologia', 80, 89.9, false),
  ('Criação de Game Profissional', 'Informática & Tecnologia', 100, 99.9, false),
  ('Criação de Loja Virtual', 'Informática & Tecnologia', 4, 59.9, false),
  ('Digitação Interativa', 'Informática & Tecnologia', 15, 69.9, false),
  ('Dropshipping', 'Informática & Tecnologia', 40, 79.9, false),
  ('Edição de Vídeo Premiere', 'Informática & Tecnologia', 13, 69.9, false),
  ('Excel Básico e Avançado', 'Informática & Tecnologia', 26, 79.9, false),
  ('Google Adwords', 'Informática & Tecnologia', 1, 49.9, false),
  ('Google Drive', 'Informática & Tecnologia', 1, 49.9, false),
  ('Illustrator 2022', 'Informática & Tecnologia', 6, 59.9, false),
  ('InDesign', 'Informática & Tecnologia', 20, 69.9, false),
  ('Introdução a Informática', 'Informática & Tecnologia', 10, 59.9, false),
  ('JavaScript', 'Informática & Tecnologia', 30, 79.9, false),
  ('Linux', 'Informática & Tecnologia', 3, 49.9, false),
  ('Lógica de Programação', 'Informática & Tecnologia', 10, 59.9, false),
  ('Manutenção de Celular', 'Informática & Tecnologia', 50, 89.9, false),
  ('Microsoft Word', 'Informática & Tecnologia', 18, 69.9, false),
  ('Montagem e Manutenção de PC', 'Informática & Tecnologia', 19, 69.9, false),
  ('Operador de Podcast', 'Informática & Tecnologia', 10, 59.9, false),
  ('PhotoShop CC', 'Informática & Tecnologia', 22, 79.9, false),
  ('Power Bi', 'Informática & Tecnologia', 30, 79.9, false),
  ('Power Point', 'Informática & Tecnologia', 20, 69.9, false),
  ('WordPress', 'Informática & Tecnologia', 120, 99.9, false),
  ('Segurança na Internet', 'Informática & Tecnologia', 20, 69.9, false),
  ('SketchUp', 'Informática & Tecnologia', 12, 69.9, false),
  ('Windows 10', 'Informática & Tecnologia', 22, 79.9, false),
  ('Windows 11', 'Informática & Tecnologia', 20, 69.9, false),
  ('Word Kids', 'Informática & Tecnologia', 40, 35.9, true),
  ('Excel Kids', 'Informática & Tecnologia', 60, 35.9, true),
  ('Celular para idosos', 'Informática & Tecnologia', 20, 69.9, false),
  ('Robótica', 'Informática & Tecnologia', 70, 89.9, false),
  ('WhatsApp Business', 'Informática & Tecnologia', 5, 59.9, false),
  ('Automação com Alexa', 'Informática & Tecnologia', 80, 89.9, false),
  ('Inteligência artificial', 'Informática & Tecnologia', 180, 99.9, false),
  ('PHP', 'Informática & Tecnologia', 180, 99.9, false),
  ('HTML e CSS', 'Informática & Tecnologia', 120, 99.9, false),
  ('Administração de empresas', 'Administrativo & Negócios', 20, 69.9, false),
  ('Agente de Portaria', 'Administrativo & Negócios', 15, 69.9, false),
  ('Almoxarifado', 'Administrativo & Negócios', 20, 69.9, false),
  ('Atendente de Farmácia', 'Administrativo & Negócios', 20, 69.9, false),
  ('Conhecimentos Bancários', 'Administrativo & Negócios', 20, 69.9, false),
  ('Contabilidade', 'Administrativo & Negócios', 22, 79.9, false),
  ('Departamento Pessoal', 'Administrativo & Negócios', 100, 99.9, false),
  ('Elaboração de Currículo', 'Administrativo & Negócios', 3, 49.9, false),
  ('Empreendedorismo', 'Administrativo & Negócios', 100, 99.9, false),
  ('Gestão em RH', 'Administrativo & Negócios', 20, 69.9, false),
  ('Hotelaria e Turismo', 'Administrativo & Negócios', 30, 79.9, false),
  ('Instagram para Vendas', 'Administrativo & Negócios', 4, 59.9, false),
  ('Investimento mercado financeiro', 'Administrativo & Negócios', 20, 69.9, false),
  ('Logística 4.0', 'Administrativo & Negócios', 50, 89.9, false),
  ('Marketing Digital', 'Administrativo & Negócios', 20, 69.9, false),
  ('Matemática financeira', 'Administrativo & Negócios', 20, 69.9, false),
  ('Mídias sociais', 'Administrativo & Negócios', 4, 59.9, false),
  ('Operador de Caixa', 'Administrativo & Negócios', 30, 79.9, false),
  ('Supervisão Pedagógica', 'Administrativo & Negócios', 60, 89.9, false),
  ('Técnicas de Vendas', 'Administrativo & Negócios', 20, 69.9, false),
  ('Telemarketing', 'Administrativo & Negócios', 18, 69.9, false),
  ('Oratória', 'Administrativo & Negócios', 30, 79.9, false),
  ('Jornalismo', 'Administrativo & Negócios', 75, 89.9, false),
  ('Corretor de Imóveis', 'Administrativo & Negócios', 60, 89.9, false),
  ('Estoque e Faturamento', 'Administrativo & Negócios', 40, 79.9, false),
  ('Artes', 'Preparatórios', 30, 79.9, false),
  ('Biologia', 'Preparatórios', 40, 79.9, false),
  ('Educação Física', 'Preparatórios', 25, 79.9, false),
  ('Filosofia', 'Preparatórios', 15, 69.9, false),
  ('Física', 'Preparatórios', 45, 89.9, false),
  ('Geografia', 'Preparatórios', 70, 89.9, false),
  ('História', 'Preparatórios', 80, 89.9, false),
  ('Matemática', 'Preparatórios', 110, 99.9, false),
  ('Matemática para Enem', 'Preparatórios', 45, 89.9, false),
  ('Português', 'Preparatórios', 40, 79.9, false),
  ('Química', 'Preparatórios', 55, 89.9, false),
  ('Sociologia', 'Preparatórios', 20, 69.9, false),
  ('Técnicas de Redação', 'Preparatórios', 30, 79.9, false),
  ('Literatura', 'Preparatórios', 35, 79.9, false),
  ('Atualização em Radiologia', 'Diversas Áreas', 40, 79.9, false),
  ('Auxiliar de Creche', 'Diversas Áreas', 20, 69.9, false),
  ('Auxiliar de Veterinário', 'Diversas Áreas', 130, 99.9, false),
  ('Barbeiro Profissional', 'Diversas Áreas', 80, 89.9, false),
  ('Designer de Cílios & Sobrancelha', 'Diversas Áreas', 15, 69.9, false),
  ('Análises Clínicas', 'Diversas Áreas', 60, 89.9, false),
  ('Energia Solar', 'Diversas Áreas', 80, 89.9, false),
  ('Agente comunitário de saúde', 'Diversas Áreas', 80, 89.9, false),
  ('Teologia Histórica', 'Diversas Áreas', 100, 99.9, false),
  ('Fiscal de Loja', 'Diversas Áreas', 10, 59.9, false),
  ('Frentista', 'Diversas Áreas', 40, 79.9, false),
  ('Manicure e Pedicure', 'Diversas Áreas', 50, 89.9, false),
  ('Maquiagem', 'Diversas Áreas', 15, 69.9, false),
  ('Massagem Modeladora', 'Diversas Áreas', 40, 79.9, false),
  ('Mediador Escolar', 'Diversas Áreas', 10, 59.9, false),
  ('NR-10', 'Diversas Áreas', 40, 79.9, false),
  ('NR-33', 'Diversas Áreas', 16, 69.9, false),
  ('NR-34', 'Diversas Áreas', 16, 69.9, false),
  ('NR-35', 'Diversas Áreas', 16, 69.9, false),
  ('Operador de Empilhadeira', 'Diversas Áreas', 30, 79.9, false),
  ('Pá Carregadeira', 'Diversas Áreas', 25, 79.9, false),
  ('Ponte Rolante', 'Diversas Áreas', 80, 89.9, false),
  ('Retroescavadeira', 'Diversas Áreas', 25, 79.9, false),
  ('Socorrista APH', 'Diversas Áreas', 24, 79.9, false),
  ('Solda MIG/MAG', 'Diversas Áreas', 32, 79.9, false),
  ('Solda TIG', 'Diversas Áreas', 30, 79.9, false),
  ('Eletricista', 'Diversas Áreas', 60, 89.9, false),
  ('TBO - Treinamento Básico Op.', 'Diversas Áreas', 35, 79.9, false),
  ('Inglês do Zero a Fluência', 'Idiomas', 100, 99.9, false),
  ('Interactive English', 'Idiomas', 100, 99.9, false),
  ('Libras', 'Idiomas', 50, 89.9, false),
  ('Espanhol', 'Idiomas', 110, 99.9, false),
  ('Windows 11 Kids', 'Informática & Tecnologia', 15, 79.9, true),
  ('Digitação Kids', 'Informática & Tecnologia', 20, 35.9, true),
  ('Power Point Kids', 'Informática & Tecnologia', 30, 35.9, true),
  ('Informática Básica Kids', 'Informática & Tecnologia', 40, 39.9, true),
  ('Programação Kids (Scratch)', 'Informática & Tecnologia', 30, 49.9, true);

on conflict (name) do nothing;

insert into public.promos (name, hours, from_price, price, icon) values
  ('Excel Básico e Avançado', 26, 99.9, 79.9, 'promo-icon-excel.webp'),
  ('Manutenção de Celular', 50, 119.9, 89.9, 'promo-icon-celular.webp'),
  ('Marketing Digital', 20, 89.9, 69.9, 'promo-icon-megafone.webp'),
  ('Programação para Iniciantes', 20, 89.9, 69.9, 'promo-icon-codigo.webp'),
  ('Inglês do Zero a Fluência', 100, 129.9, 99.9, 'promo-icon-chat.webp');

on conflict (name) do nothing;
